feat: Post endpoint
elixir-cloud-aai/drs-filer pull request #9
Opened 2020-08-01 09:55 UTC by sarthakgupta072

## Description

Implement post endpoint. The fields like `id`, `self_uri` and `access_id` are auto-populated based on the DRS specs.

Fixes #8 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:

- [x] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not reduced the existing code coverage
- [x] I have added docstrings following the [Python style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/python.md) of this project to all new modules, classes, methods and functions are documented with docstrings following; I have updated any previously existing docstrings, if applicable
- [x] I have updated any sections of the app's documentation that are affected by the proposed changes, if applicable

2020-08-10 12:05 UTC, uniqueg requested changes

2020-08-10 12:05 UTC, uniqueg commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +MAIN_FIELDS_TO_OMIT = ["id", "self_uri"]
Please add a new model for `POST` and remove these hacks.

2020-08-10 12:05 UTC, uniqueg commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +CHARSET = string.ascii_letters + string.digits + ".-_~"
Please add these to the config file. You can [add any sections you want to the FOCA config file](https://github.com/elixir-cloud-aai/foca/blob/30029539de172973dd0a82958bab32fc9ecce840/foca/models/config.py#L1134), apart from the reserved ones (e.g., `server`, `api`), and they will be added to the Flask config just like all the other params.
When you do that, set up support for _different_ settings for the object and access method IDs, because service admins may want to reduce the chance of users mixing them up (e.g., uppercase vs lowercase or whatever). You can use the same defaults if you like (although different might be better to illustrate the behavior), just make sure you have: `object_id_charset`, `object_id_length`, `access_id_charset` and `access_id_length` under some new section, e.g., `endpoints`.

You could also nest them if you prefer that:
```yaml
endpoints:
  objects:
    id_charset: # set some default
    id_length: # set some default
  access_methods:
    id_charset: # set some default
    id_length: # set some default
```

But how you organize the settings is not important, we can change it anytime later, so no need to think about it too much.

2020-08-10 12:05 UTC, uniqueg commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +            generated_object_id = _create_id()
Pass the config vars (see comment above) as arguments, do not use global vars.

2020-08-10 12:05 UTC, uniqueg commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +                generated_access_id = _create_id()
You need to consider the possibility that an `access_id` already exists when adding an _additional_ access method to an existing object. While there is no way of doing this now, there will be in the future, so best to already prepare for this. If you raise a specific error when trying to add an access method with a generated ID, I think you can just add the code for parsing/adding access methods inside the `while` loop in the main function (rather than before) and catch/handle it together with the `DuplicateKeyError` like so:

```
except (DuplicateKeyError, DuplicateAccessIDError):
    continue
```

2020-08-10 12:05 UTC, uniqueg commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +def _prepare_access_data(data: Dict) -> Dict:
After adding new models for the POST endpoint (smaller versions of `Object` and `AccessMethod`; see comment above), most of this should not be necessary. Pretty much just the generation of an `access_id` will remain.

2020-08-12 10:50 UTC, sarthakgupta072 commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +                generated_access_id = _create_id()
Right now, we are adding `POST` endpoint only, right? So, `DuplicateAccessIDError` won't occur, no?

2020-08-12 12:42 UTC, uniqueg commented on drs_filer/ga4gh/drs/endpoints/register_new_objects.py
> +                generated_access_id = _create_id()
Yes, for `POST` in principle you only need to make sure that if there are multiple access methods, their randomly generated `access_id`s need to be different. Only in a `PUT`/`PATCH` endpoint, you would need to (futher) ensure that conflicts with already existing `access_id`s in the database are prevented.

2020-08-14 13:45 UTC, merged